### ISSUE TITLE
Version fix?

### ISSUE THREAD

**Issue by AndreasFromDanmark** [jimathy/jim-trains#1]
![image](https://github.com/jimathy/jim-trains/assets/35656492/4bb45941-aa7b-4a31-b8a8-44b63b80acd7)

**Comment by jimathy** [comment]
github being dumb, ill try fix it now

**Comment by AndreasFromDanmark** [comment]
@jimathy Thanks :)

**Comment by AndreasFromDanmark** [comment]
@jimathy Its fixed now :)
![image](https://github.com/jimathy/jim-trains/assets/35656492/010f609a-568e-4395-baf2-46c25aed5c33)
